const transcripcionDet2 = `Hola, hoy preparamos espaguetis a la carbonara, pero la receta auténtica, la que no lleva nata. Empiezo rayando el queso pecorino, que es el queso que se utiliza para hacer esta receta. Para dos personas necesito cien gramos de queso. De todas maneras, te he dejado todas las cantidades de esta receta al final del vídeo y abajo en la descripción. Otro ingrediente que lleva la carbonara es el guanciale. En este caso he comprado papada, pero si encuentras el guanciale, mucho mejor. Si no lo encuentras,
      siempre puedes utilizar panceta o beicon. Vamos a hacer unos daditos y así tendremos todos los ingredientes preparados porque esta receta es rapidísima. Ya tenemos la papada cortadita. Ahora vamos a freír la papada y como ves no le he echado nada de aceite a la sartén. Dejaremos que se tueste por fuera
      y por dentro seguirá tierna. Hay que ir moviendo constantemente para que no se queme y ahora que ya está bien doradita lo que voy a hacer es reservarla. Para hervir la pasta se calienta abundante agua y se le echa un puñadito de sal. Cuando hierva el agua se echa la pasta. En este caso estos espaguetis tienen que cocer durante ocho minutos. Mientras cuece la pasta vamos a poner las yemas en un bol y le añadimos pimienta.
      Lo batimos y aquí le añadiremos el queso. Lo añado poco a poco para mezclarlo mejor. Como esta mezcla es muy espesa se le echa un poco de agua de cocción de los espaguetis. Como ves así va admitiendo más queso. Y ahora que ya lo tenemos todo integrado
      lo reservamos. Ya han pasado los nueve minutos, voy a apagar este fuego y ahora vamos a pasar los espaguetis a la sartén donde tenemos el guanciale. Con el fuego bien bajito lo mantenemos caliente y lo movemos. Y ahora le vamos a añadir la crema de las yemas. Y vamos a mover
      y nos tiene que quedar unos espaguetis supercremosos. Eso sí, que no se nos cuaje el huevo. Le añadimos un cacito de la cocción y ahora hay que remover enérgicamente hasta que nos queden bien cremositos. Mira, mira qué cremosidad. Pues momento de servir.
      Un poquito más y terminamos con una pizquita de pimienta negra y un poquito más de queso. Pues momento de probar. Mmm Pues así es como se hacen los espaguetis a la carbonara. Te aseguro que han quedado riquísimos, así que te animo a que los prepares. Si te ha gustado el vídeo
      no olvides darle al like. Nos vemos en el siguiente vídeo. GraciasHola, hoy preparamos espaguetis a la carbonara, pero la receta auténtica, la que no lleva nata. Empiezo rayando el queso pecorino, que es el queso que se utiliza para hacer esta receta. Para dos personas necesito cien gramos de queso. De todas maneras, te he dejado todas las cantidades de esta receta al final del vídeo y abajo en la descripción. Otro ingrediente que lleva la carbonara es el guanciale. En este caso he comprado papada, pero si encuentras el guanciale, mucho mejor. Si no lo encuentras,
      siempre puedes utilizar panceta o beicon. Vamos a hacer unos daditos y así tendremos todos los ingredientes preparados porque esta receta es rapidísima. Ya tenemos la papada cortadita. Ahora vamos a freír la papada y como ves no le he echado nada de aceite a la sartén. Dejaremos que se tueste por fuera
      y por dentro seguirá tierna. Hay que ir moviendo constantemente para que no se queme y ahora que ya está bien doradita lo que voy a hacer es reservarla. Para hervir la pasta se calienta abundante agua y se le echa un puñadito de sal. Cuando hierva el agua se echa la pasta. En este caso estos espaguetis tienen que cocer durante ocho minutos. Mientras cuece la pasta vamos a poner las yemas en un bol y le añadimos pimienta.
      Lo batimos y aquí le añadiremos el queso. Lo añado poco a poco para mezclarlo mejor. Como esta mezcla es muy espesa se le echa un poco de agua de cocción de los espaguetis. Como ves así va admitiendo más queso. Y ahora que ya lo tenemos todo integrado
      lo reservamos. Ya han pasado los nueve minutos, voy a apagar este fuego y ahora vamos a pasar los espaguetis a la sartén donde tenemos el guanciale. Con el fuego bien bajito lo mantenemos caliente y lo movemos. Y ahora le vamos a añadir la crema de las yemas. Y vamos a mover
      y nos tiene que quedar unos espaguetis supercremosos. Eso sí, que no se nos cuaje el huevo. Le añadimos un cacito de la cocción y ahora hay que remover enérgicamente hasta que nos queden bien cremositos. Mira, mira qué cremosidad. Pues momento de servir.
      Un poquito más y terminamos con una pizquita de pimienta negra y un poquito más de queso. Pues momento de probar. Mmm Pues así es como se hacen los espaguetis a la carbonara. Te aseguro que han quedado riquísimos, así que te animo a que los prepares. Si te ha gustado el vídeo
      no olvides darle al like. Nos vemos en el siguiente vídeo. Gracias`;

export default transcripcionDet2;