const transcripcionDet4 = `El risotto es un platillo fabuloso, pero puede parecer complicado si no se siguen algunas reglas importantes. Así que vamos a enfocarnos en cada uno de los pasos para lograr un risotto absolutamente perfecto. El risotto es tradicionalmente hecho con arroz arborio, que es un tipo de grano corto de arroz. Tiene un alto contenido de almidón, que permite que sea más cremoso cuando se cuece. Puedes usar otro tipo de arroz o granos, como arroz de grano largo, farro o cebada, pero recomendamos el arborio. No hay una forma rápida
      y fácil de conseguir la consistencia ideal, pero una buena regla a seguir es que por cada taza de arroz hay que usar de cuatro a seis tazas de caldo. Aquí usaremos caldo de pollo, pero puedes usar el que quieras o incluso agua si prefieres. A fuego alto, vamos a hervir el caldo, porque si agregas caldo frío a tu arroz, no se cocerá por completo ni tendrá la textura cremosa que queremos. Ahora elijamos nuestra olla. Asegúrate de usar una olla alta porque estarás agregando cada vez más caldo y hará que el arroz duplique su tamaño. Si la olla es muy pequeña,
      se va a desbordar. Una vez que el caldo esté hirviendo, baja la flama o tenlo cerca. Lo importante es que el caldo se mantenga calientito. Ahora pon tu olla a fuego medio y agrega un poco de aceite. Una vez que se caliente, agrega tu allium de preferencia. Nosotros usaremos echalotes. Allium es el nombre del grupo al que también pertenecen las cebollas, el cebollín y el ajo. Entonces, vas a cocinarlos hasta que se transparenten. Y luego hay que agregar las setas y la mantequilla y cocinar hasta que se suavicen.
      Esto va a tomar tiempo, así que ten paciencia. Y si no te gustan las setas, puedes omitir este paso y agregar directo el arroz. Una vez que se cocinen, agrega ajo, tomillo, sal y pimienta. Esto es para darle más sabor, pero puedes experimentar con diferentes especias, las que tú quieras. Es tiempo de agregar el arroz. Revuelve bien hasta mezclar todo. Queremos tostar el arroz, pero no quemarlo, así que solo serán uno o dos minutos. Después agrega un chorrito de vino blanco
      para darle un poco de acidez. Si no quieres usar alcohol, puedes intercambiarlo por jugo de limón. Cuando el alcohol se haya evaporado, será momento de agregar el caldo poco a poco La paciencia es una virtud, especialmente con el risotto. (se ríe) Solo debes agregar caldo suficiente para cubrir el arroz y revolver constantemente hasta que lo absorba (pausa de tres segundos). Sigue echando caldo poco a poco hasta que el arroz esté al dente. Serán unos quince a veinte minutos.
      Vas a saber que está listo cuando el arroz tenga un poco de firmeza y la textura sea cremosa. Si pasas la cuchara y el arroz poco a poco regresa a su lugar, está listo. Para un extra de cremosidad y sabor, agrega queso parmesano rallado y mezcla. Y ya, eso es todo. El risotto realmente no es complicado, siempre y cuando recuerdes los principios básicos. Tómate tu tiempo, sé paciente y sigue las reglas. Te prometemos que serás un maestro del risotto en poco tiempo
      (se ríe). Me encanta. El arroz es perfecto en todas sus presentaciones. Y el risotto es como su versión fancy (se ríe)
      (Música instrumental).`;

export default transcripcionDet4;